<?php
// $Id: workflow_extensions.install,v 1.1 2010/10/20 23:43:29 rdeboer Exp $

/**
 * @file
 * Install and uninstall hooks for Workflow extensions module.
 */

/**
 * Implementation of hook_install().
 *
function workflow_extensions_install() {
}
 */

/**
 * Implementation of hook_uninstall().
 */
function workflow_extensions_uninstall() {
  // Delete all workflow_extensions_* variables at once
  db_query("DELETE FROM {variable} WHERE name LIKE 'workflow_extensions_%%'");
}