<?php
// $Id: comment_service.module,v 1.1.2.1.2.9 2010/07/16 02:59:56 skyredwang Exp $

/**
 * @file
 *  Link commenting functionality to services module.
 */

/**
 * Implementation of hook_perm().
 */
function comment_tvchat_service_perm() {
  return array('access comments from remote', 'save comments from remote');
}
/**
 * Implementation of hook_service().
 */
function comment_tvchat_service_service() {
  return array(

    // comment.delete
    array(
      '#method'   => 'comment.delete',
      '#callback' => 'comment_service_delete',
      '#access arguments'  => array('access comments from remote'),
      '#file'     => array('file' => 'inc', 'module' => 'comment_service', 'file name' => 'comment_service_tvchat'),
      '#args'      => array(
        array(
          '#name'         => 'cid',
          '#type'         => 'int',
          '#description'  => t('A comment id'),
        ),
      ),
      '#return' => 'boolean',
      '#help'   => t('This method delete a comment.'),
    ),
  );
}
