<?php
// $Id: user_service.module,v 1.3.2.16.2.7 2010/05/22 22:56:23 heyrocker Exp $

/**
 * @file
 *  Link general user functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function user_tvchat_service_perm() {
  return array(
    'get any user data', 'get own user data',
    'update any user data', 'update own user data',
    'create new users',
    'delete any user', 'delete own user',
    'user_service from remote',
  );
}

/**
 * Implementation of hook_service().
 */
function user_tvchat_service_service() {
  return array(

    // user.update
    array(
      '#method'           => 'user.update',
      '#callback'         => 'user_tvchat_service_update',
      '#access arguments' => array('user_service from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'user_tvchat_service'),
      '#args'             => array(
        array(
          '#name'           => 'nick',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('user nickname. profile nickname.'),
        ), 
        array(
          '#name'           => 'todayMessage',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('user nickname. profile nickname.'),
        ), 
        array(
          '#name'           => 'fname',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file name including extension.'),
        ), 
        array(
          '#name'           => 'picture',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file data base64 encoded.'),
        ), 
        array(
          '#name'           => 'message_alarm',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('message alram flag (0 or 1)'),
        ), 
        array(
          '#name'           => 'tvshow_alarm',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('tvshow alram flag (0 or 1)'),
        ), 
        array(
          '#name'           => 'fb_id',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('facebook id '),
        ), 
        array(
          '#name'           => 'token_APNS',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('device token for APNS'),
        ),
        array(
          '#name'           => 'phone_number',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('phone number'),
        ),
        array(
          '#name'           => 'email',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('email address'),
        ), 
      ),
      '#return'           => 'int',
      '#help'             => t('Save user details.')
    ),

    // user.changePassword
    array(
      '#method'           => 'user.changePassword',
      '#callback'         => 'user_tvchat_service_changePassword',
      '#access arguments' => array('user_service from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'user_tvchat_service'),
      '#args'             => array(
        array(
          '#name'           => 'newPassword',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('user new passowrd .'),
        ), 
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#optional'       => true,
          '#description'    => t('A user id.'),
        ),        
              ),
      '#return'           => 'bool',
      '#help'             => t('Save user details.')
    ), 

    // user.signup
    array(
      '#method'           => 'user.signup',
      '#callback'         => 'user_tvchat_service_signup',
      '#access arguments' => array('user_service from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'user_tvchat_service'),
      '#args'             => array(
        array(
          '#name'           => 'nick',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('user nickname. profile nickname.'),
        ), 
        array(
          '#name'           => 'email',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('email address. profile nickname.'),
        ), 
        array(
          '#name'           => 'phone_number',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('user phone number'),
        ),
        array(
          '#name'           => 'fname',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file name including extension.'),
        ), 
        array(
          '#name'           => 'picture',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file data base64 encoded.'),
        ), 
        array(
          '#name'           => 'token_APNS',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('device token for APNS'),
        ), 
        array(
          '#name'           => 'status',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('1- active, 0 - blocked'),
        ), 
      ),
      '#return'           => 'struct',
      '#help'             => t('Save user details.')
    ),
  );
}
