CREATE TABLE TELINK_SMS
(
CMP_MSG_ID VARCHAR(20) NOT NULL PRIMARY KEY,
CMP_USR_ID VARCHAR(5) NOT NULL,
ODR_FG CHAR(1) NOT NULL,
SMS_GB CHAR(1) NOT NULL,
USED_CD CHAR(3) NOT NULL,
MSG_GB CHAR(1) NOT NULL,
WRT_DTTM CHAR(14),
SND_DTTM CHAR(14) NOT NULL,
SND_PHN_ID VARCHAR(15),
RCV_PHN_ID VARCHAR(15) NOT NULL,
CALLBACK VARCHAR(15),
SND_MSG VARCHAR(200) NOT NULL,
CMP_SND_DTTM CHAR(14),
CMP_RCV_DTTM CHAR(14),
REG_SND_DTTM CHAR(14),
REG_RCV_DTTM CHAR(14),
EXPIRE_VAL INT NOT NULL,
SMS_ST CHAR(1) NOT NULL,
RSLT_VAL INT,
RSRVD_ID VARCHAR(20),
RERVD_WD VARCHAR(50),
DEL_FLAG CHAR(1)
)
GO

CREATE UNIQUE INDEX TELINK_SMS_IDX
ON TELINK_SMS(CMP_MSG_ID)
GO

CREATE INDEX TELINK_SMS_IDX1
ON TELINK_SMS(SMS_ST)
GO

CREATE INDEX TELINK_SMS_IDX2
ON TELINK_SMS(SND_DTTM)
GO

CREATE INDEX TELINK_SMS_MSG_IDX
ON TELINK_SMS(SMS_ST,SND_DTTM)
GO





