
CREATE TABLE TELINK_SMS
(
  CMP_MSG_ID    VARCHAR2(20 BYTE),
  CMP_USR_ID    VARCHAR2(5 BYTE),
  ODR_FG        CHAR(1 BYTE),
  SMS_GB        CHAR(1 BYTE),
  USED_CD       CHAR(3 BYTE),
  MSG_GB        CHAR(1 BYTE),
  WRT_DTTM      CHAR(14 BYTE),
  SND_DTTM      CHAR(14 BYTE),
  SND_PHN_ID    VARCHAR2(15 BYTE),
  RCV_PHN_ID    VARCHAR2(15 BYTE),
  CALLBACK      VARCHAR2(15 BYTE),
  SND_MSG       VARCHAR2(200 BYTE),
  CMP_SND_DTTM  CHAR(14 BYTE),
  CMP_RCV_DTTM  CHAR(14 BYTE),
  REG_SND_DTTM  CHAR(14 BYTE),
  REG_RCV_DTTM  CHAR(14 BYTE),
  EXPIRE_VAL    NUMBER,
  SMS_ST        CHAR(1 BYTE),
  RSLT_VAL      NUMBER(4),
  RSRVD_ID      VARCHAR2(20 BYTE),
  RSRVD_WD      VARCHAR2(50 BYTE),
  DEL_FLAG      CHAR(1 BYTE)
)
TABLESPACE WEBDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX DEL_FLAG_IDX ON TELINK_SMS
(DEL_FLAG)
LOGGING
TABLESPACE WEB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TELINK_SMS_IDX ON TELINK_SMS
(CMP_MSG_ID)
LOGGING
TABLESPACE WEB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE INDEX _TABLE_NAME_STSND_IDX ON _TABLE_NAME_
(SMS_ST, SND_DTTM)
LOGGING
TABLESPACE WEB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TELINK_SMS_MSG_IDX3 ON TELINK_SMS
(SMS_ST, SND_DTTM, RCV_PHN_ID)
LOGGING
TABLESPACE WEB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TELINK_SMS_MSG_IDX4 ON TELINK_SMS
(RSRVD_ID, SMS_ST, RCV_PHN_ID, SND_DTTM)
LOGGING
TABLESPACE WEB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;