<?php

// $Id$

/**
 * @file
 *  Link general privatemsg module functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function privatemsg_tvchat_service_perm() {
  return array(
    'get private messages from remote',
    'send private messages from remote',
  );
}

/**
 * Implementation of hook_service().
 */
function privatemsg_tvchat_service_service() {
  return array(

   array(
        '#method'           => 'privatemsg.getUids',
        '#callback'         => 'privatemsg_tvchat_service_get_uids',
        '#access arguments' => array('get private messages from remote'),
        '#file'             => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
        '#args'             => array(
            array(
                  '#name'         => 'uid',
                  '#type'         => 'int',
                  '#optional'     => TRUE,
                  '#description'  => t('The ID of the user who logged in.')
                  ),
              ),
          '#return'           => 'array',
          '#help'             => t('Get users who communicate with private messages.')
    ),

    array(
      '#method'           => 'privatemsg.getMsg',
      '#callback'         => 'privatemsg_tvchat_service_get_msg',
      '#access arguments' => array('get private messages from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
      '#args'             => array(
        array(
          '#name'         => 'fr_uid',
          '#type'         => 'int',
          '#optional'     => FALSE,
          '#description'  => t('The friend\'s id')
        ), 
        array(
          '#name'         => 'uid',
          '#type'         => 'int',
          '#optional'     => TRUE,
          '#description'  => t('The ID of the user who logged in.')
        ),
                array(
          '#name'           => 'offset',
          '#type'           => 'int',
          '#optional'       => TRUE,
          '#description'    => t('An offset integer for paging.')
        ),
        array(
          '#name'           => 'limit',
          '#type'           => 'int',
          '#optional'       => TRUE,
          '#description'    => t('A limit integer for paging.')
        ),

      ),
      '#return'           => 'array',
      '#help'             => t('Get users who communicate with private messages.')
    ),

    array(
      '#method'           => 'privatemsg.getMsgWithRecipientUid',
      '#callback'         => 'privatemsg_tvchat_service_get_msg_with_recipient_uid',
      '#access arguments' => array('get private messages from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
      '#args'             => array(
        array(
          '#name'         => 'recipient_uid',
          '#type'         => 'int',
          '#optional'     => FALSE,
          '#description'  => t('The friend\'s id')
        ), 
        array(
          '#name'         => 'offset',
          '#type'         => 'int',
          '#optional'     => TRUE,
          '#description'  => t('Offset , default = 0')
        ), 

      ),
      '#return'           => 'struct',
      '#help'             => t('Get message list who communicate with private messages.')
    ),

    // privatemsg.getThread
    array(
      '#method'     => 'privatemsg.getThread',
      '#callback'   => 'privatemsg_tvchat_service_get_thread',
      '#access arguments' => array('get private messages from remote'),
      '#file'       => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
      '#args'       => array(
        array(
            '#name'         => 'thread_id',
            '#type'         => 'int',
            '#description'=> t('The ID of the thread that should be retrieved.')
        ),
        array(
            '#name'         => 'offset',
            '#type'         => 'int',
            '#optional'     => TRUE,
            '#description'  => t('Message offset from the start of the thread.')
                    ),
                ),
            '#return'           => 'array',
            '#help'             => t('Get all messages in a thread. User needs to be logged in. Unless the logged-in user has the \'read all private messages\' permission, the user will only be able to get threads that he/she participated in.')
         ),


    array(
      '#method'           => 'privatemsg.sendWithUids',
      '#callback'         => 'privatemsg_tvchat_service_send_with_uids',
      '#access arguments' => array('get private messages from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
      '#args'             => array(
        array(
          '#name'         => 'recipient_uids',
          '#type'         => 'array',
          '#optional'     => FALSE,
          '#description'  => t('Recipient uid list')
        ), 
        array(
          '#name'         => 'body',
          '#type'         => 'string',
          '#optional'     => FALSE,
          '#description'  => t('subject')
        ), 
        array(
          '#name'         => 'subject',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('subject')
        ),
        array(
          '#name'         => 'fname',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('subject')
        ), 
        array(
          '#name'         => 'attachment',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('subject')
        ), 
      ),
      '#return'           => 'struct',
      '#help'             => t('Get message list who communicate with private messages.')
    ),

    array(
      '#method'           => 'privatemsg.sendWithThreadId',
      '#callback'         => 'privatemsg_tvchat_service_send_with_thread_id',
      '#access arguments' => array('get private messages from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'privatemsg_tvchat_service'),
      '#args'             => array(
        array(
          '#name'         => 'author_uid',
          '#type'         => 'int',
          '#optional'     => FALSE,
          '#description'  => t('Author\'s uid')
        ), 
        array(
          '#name'         => 'body',
          '#type'         => 'string',
          '#optional'     => FALSE,
          '#description'  => t('subject')
        ), 
        array(
          '#name'         => 'thread_id',
          '#type'         => 'int',
          '#optional'     => FALSE,
          '#description'  => t('subject')
        ), 
        array(
          '#name'         => 'fname',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('subject')
        ), 
        array(
          '#name'         => 'attachment',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('subject')
        ), 
      ),
      '#return'           => 'struct',
      '#help'             => t('Get message list who communicate with private messages with thread id.')
    ),
  );
}
